"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import * as Tabs from "@radix-ui/react-tabs";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Building2, Clock3, Database, Eye, GitCompareArrows, Globe, Lock, Radar, ShieldCheck, TriangleAlert } from "lucide-react";
import { toast } from "sonner";
import type { Company } from "../../../types/company";
import type { ComplaintDisplay } from "../../../types/complaint";
import { Card, CardContent, CardHeader, CardTitle } from "../../../components/ui/Card";
import { Button } from "../../../components/ui/Button";
import { FeatureItem } from "../../relatorio/components/FeatureItem";
import { getPusherClient } from "../../../lib/realtime/pusher-client";
import { AdminGodModeBar } from "../../../components/empresa/AdminGodModeBar";
import { Dialog, DialogClose, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "../../../components/ui/Dialog";
import { useI18n } from "../../../components/providers/I18nProvider";

/** Descrição gerada no backoffice (várias línguas) — mostrar com a locale atual. */
function isAutoGeneratedOfficialCompanyDescription(description: string, companyName: string): boolean {
  const trimmed = description.trim();
  if (!trimmed || !companyName) return false;
  const escaped = companyName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return (
    new RegExp(`^Perfil oficial de ${escaped}\\.?$`, "i").test(trimmed) ||
    new RegExp(`^Official profile for ${escaped}\\.?$`, "i").test(trimmed)
  );
}

export type EmpresaTab = "latest" | "unanswered" | "responded";

interface EmpresaViewProps {
  company: Company;
  complaints: ComplaintDisplay[];
  reputation: {
    score: number;
    responseRate: number;
    solutionRate: number;
    avgRating: number;
  };
  initialTab: EmpresaTab;
  initialQ: string;
  initialStatus: string;
  initialCity: string;
  isOwner: boolean;
  isAdmin: boolean;
  performance: {
    avgResponseHours: number;
    solutionIndex: number;
  };
  /** Utilizador autenticado: abre o modal lateral na home com empresa pré-preenchida. */
  complaintUserId: string | null;
}

export function EmpresaView({
  company,
  complaints,
  reputation,
  initialTab,
  initialQ,
  initialStatus,
  initialCity,
  isOwner,
  isAdmin,
  performance,
  complaintUserId,
}: EmpresaViewProps) {
  const router = useRouter();
  const { t, locale: appLocale } = useI18n();
  const dateLocaleTag = appLocale === "en" ? "en-GB" : appLocale === "es" ? "es" : "pt-PT";
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const [tab, setTab] = useState<EmpresaTab>(initialTab);
  const [query, setQuery] = useState(initialQ);
  const [city, setCity] = useState(initialCity);
  const [status, setStatus] = useState(initialStatus);
  const [viewCount, setViewCount] = useState(company.views_count ?? 0);
  const [dateMap, setDateMap] = useState<Record<string, string>>({});
  const [compareOpen, setCompareOpen] = useState(false);
  const [compareLoading, setCompareLoading] = useState(false);
  const [compareData, setCompareData] = useState<{
    companyName: string;
    reputation: { score: number; responseRate: number; solutionRate: number };
    performance: { avgResponseHours: number; solutionIndex: number };
    position: number | null;
    percentile: number | null;
  } | null>(null);

  useEffect(() => {
    const map: Record<string, string> = {};
    for (const complaint of complaints) {
      map[complaint.id] = new Date(complaint.created_at).toLocaleString(dateLocaleTag);
    }
    setDateMap(map);
  }, [complaints, dateLocaleTag]);

  useEffect(() => {
    const params = new URLSearchParams(searchParams.toString());
    params.set("tab", tab);
    if (query) params.set("q", query);
    else params.delete("q");
    if (city) params.set("city", city);
    else params.delete("city");
    if (status) params.set("status", status);
    else params.delete("status");
    router.replace(`${pathname}?${params.toString()}`);
  }, [tab, query, city, status, pathname, router, searchParams]);

  useEffect(() => {
    void fetch(`/api/v1/company/public/${company.slug}/view`, {
      method: "POST",
    }).then(async (res) => {
      const payload = await res.json().catch(() => null);
      if (res.ok && typeof payload?.data?.views === "number") {
        setViewCount(payload.data.views);
      }
    });
  }, [company.slug]);

  useEffect(() => {
    const pusher = getPusherClient();
    if (!pusher) return;
    const companyChannel = pusher.subscribe(`company-${company.slug}`);
    const feedChannel = pusher.subscribe("complaints-feed");
    companyChannel.bind("views-updated", (data: { views?: number }) => {
      if (typeof data.views === "number") setViewCount(data.views);
    });
    feedChannel.bind("complaint-updated", () => {
      router.refresh();
      toast.success(t("empresa.feedUpdated"));
    });
    return () => {
      companyChannel.unbind_all();
      feedChannel.unbind_all();
      pusher.unsubscribe(`company-${company.slug}`);
      pusher.unsubscribe("complaints-feed");
    };
  }, [company.slug, router, t]);

  const seal = useMemo(() => {
    if (reputation.score >= 8) return t("empresa.sealElite");
    if (reputation.score >= 6) return t("empresa.sealGreat");
    if (reputation.score >= 4) return t("empresa.sealRegular");
    return t("empresa.sealLow");
  }, [reputation.score, t]);

  async function handleOpenCompare() {
    setCompareOpen(true);
    setCompareLoading(true);
    try {
      const response = await fetch(`/api/v1/company/public/${company.slug}/compare`, { credentials: "include" });
      const payload = await response.json().catch(() => null);
      if (!response.ok) {
        toast.error(payload?.error?.message ?? t("empresa.compareError"));
        return;
      }
      setCompareData(payload?.data ?? null);
    } finally {
      setCompareLoading(false);
    }
  }

  return (
    <div suppressHydrationWarning className="min-h-screen px-4 py-6 md:px-8">
      <div className="mx-auto max-w-7xl">
        <header className="sticky top-3 z-20 mb-6 rounded-2xl border border-zinc-200/90 bg-white/85 p-4 shadow-sm backdrop-blur-md transition hover:border-zinc-300/90 hover:shadow-md dark:border-transparent dark:bg-zinc-950/55 dark:shadow-none dark:ring-1 dark:ring-zinc-800/80 dark:hover:bg-zinc-950/75 md:p-6">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div className="flex min-w-0 flex-1 items-center gap-4">
              <div className="flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-full bg-emerald-500/15 ring-1 ring-emerald-500/35 dark:bg-emerald-500/20 dark:ring-emerald-500/40">
                {company.logo_image ? (
                  <Image
                    src={company.logo_image}
                    alt={company.name}
                    width={56}
                    height={56}
                    className="h-full w-full object-cover"
                    unoptimized
                  />
                ) : (
                  <Building2 className="h-7 w-7 text-emerald-700 dark:text-emerald-300" />
                )}
              </div>
              <div className="min-w-0">
                <div className="text-xs text-zinc-600 dark:text-zinc-400">
                  <Link href="/" className="hover:text-zinc-900 dark:hover:text-zinc-200">
                    {t("nav.home")}
                  </Link>{" "}
                  / <span>{t("nav.company")}</span> / <span className="truncate">{company.name}</span>
                </div>
                <h1 className="truncate text-xl font-semibold tracking-tight text-zinc-900 dark:text-zinc-100">{company.name}</h1>
                <div className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-zinc-600 dark:text-zinc-400">
                  {company.website ? (
                    <a href={company.website} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-emerald-700 hover:text-emerald-600 dark:text-emerald-300 dark:hover:text-emerald-200">
                      <Globe className="h-3.5 w-3.5" />
                      {t("empresa.officialWebsite")}
                    </a>
                  ) : null}
                  <span>
                    {t("empresa.taxId")}: {company.taxId || t("common.notInformed")}
                  </span>
                </div>
                {company.description ? (
                  <p className="mt-1 line-clamp-2 max-w-2xl text-xs text-zinc-600 dark:text-zinc-400">
                    {isAutoGeneratedOfficialCompanyDescription(company.description, company.name)
                      ? t("company.autoOfficialDescription").replace("{{name}}", company.name)
                      : company.description}
                  </p>
                ) : null}
              </div>
            </div>
            <div className="flex w-full flex-wrap items-center gap-2 text-sm text-zinc-700 sm:w-auto dark:text-zinc-300">
              <Eye className="h-4 w-4 text-emerald-600 dark:text-emerald-300" />
              <span>
                {viewCount.toLocaleString(dateLocaleTag)} {t("empresa.views")}
              </span>
              <Dialog open={compareOpen} onOpenChange={setCompareOpen}>
                <DialogTrigger asChild>
                  <Button size="sm" variant="outline" onClick={handleOpenCompare}>
                    <GitCompareArrows className="h-4 w-4" />
                    {t("empresa.compare")}
                  </Button>
                </DialogTrigger>
                <DialogContent>
                  <DialogHeader>
                    <DialogTitle>{t("empresa.compareTitle")}</DialogTitle>
                  </DialogHeader>
                  {compareLoading ? (
                    <p className="text-sm text-zinc-600 dark:text-zinc-300">{t("empresa.compareLoading")}</p>
                  ) : compareData ? (
                    <div className="space-y-3">
                      <p className="text-sm text-zinc-800 dark:text-zinc-200">
                        {t("empresa.compareLine")
                          .replace("{{company}}", compareData.companyName)
                          .replace(
                            "{{position}}",
                            compareData.position ? `#${compareData.position}` : t("empresa.positionUnknown")
                          )}
                      </p>
                      <div className="grid grid-cols-2 gap-2 text-sm">
                        <div className="rounded-xl bg-zinc-100/90 p-3 ring-1 ring-zinc-200/90 dark:bg-zinc-950/50 dark:ring-zinc-800/80">
                          {t("empresa.compareMetricNote")} {compareData.reputation.score.toFixed(2)}
                        </div>
                        <div className="rounded-xl bg-zinc-100/90 p-3 ring-1 ring-zinc-200/90 dark:bg-zinc-950/50 dark:ring-zinc-800/80">
                          {t("empresa.compareMetricSolution")} {compareData.performance.solutionIndex.toFixed(1)}%
                        </div>
                        <div className="rounded-xl bg-zinc-100/90 p-3 ring-1 ring-zinc-200/90 dark:bg-zinc-950/50 dark:ring-zinc-800/80">
                          {t("empresa.compareMetricResponse")} {compareData.performance.avgResponseHours.toFixed(1)}h
                        </div>
                        <div className="rounded-xl bg-zinc-100/90 p-3 ring-1 ring-zinc-200/90 dark:bg-zinc-950/50 dark:ring-zinc-800/80">
                          {t("empresa.compareMetricPercentile")}{" "}
                          {compareData.percentile != null ? `${compareData.percentile.toFixed(0)}%` : "-"}
                        </div>
                      </div>
                      <DialogClose className="rounded-lg border border-zinc-300/90 px-3 py-2 text-sm hover:bg-zinc-100 dark:border-zinc-700 dark:hover:bg-zinc-900/40">
                        {t("common.close")}
                      </DialogClose>
                    </div>
                  ) : (
                    <p className="text-sm text-zinc-600 dark:text-zinc-300">{t("empresa.compareNoData")}</p>
                  )}
                </DialogContent>
              </Dialog>
              <Button
                size="sm"
                variant="outline"
                onClick={async () => {
                  if (!complaintUserId) {
                    router.push(`/login?from=${encodeURIComponent(pathname)}`);
                    toast.info(t("empresa.chatLogin"));
                    return;
                  }
                  const response = await fetch("/api/v1/inbox/conversations", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    credentials: "include",
                    body: JSON.stringify({ companyId: company.id }),
                  });
                  const payload = await response.json().catch(() => null);
                  if (!response.ok) {
                    toast.error(payload?.error?.message ?? t("empresa.chatOpenError"));
                    return;
                  }
                  const conversationId = String(payload?.data?.conversationId ?? "");
                  router.push(conversationId ? `/inbox?conversation=${encodeURIComponent(conversationId)}` : "/inbox");
                }}
              >
                {t("empresa.directMessage")}
              </Button>
              <Button
                size="sm"
                onClick={() => {
                  const qs = new URLSearchParams({
                    openComplaint: "1",
                    complaintCompany: company.id,
                    complaintCname: company.name,
                  });
                  const target = `/?${qs.toString()}`;
                  if (complaintUserId) {
                    router.push(target);
                    toast.success(t("empresa.complaintFormOpened"));
                  } else {
                    router.push(`/login?from=${encodeURIComponent(target)}`);
                    toast.info(t("empresa.complaintLogin"));
                  }
                }}
              >
                {t("empresa.complain")}
              </Button>
            </div>
          </div>
        </header>
        {isAdmin && <AdminGodModeBar companySlug={company.slug} />}

        <div className="grid grid-cols-12 gap-4">
          <aside className="col-span-12 space-y-4 lg:col-span-3 lg:sticky lg:top-24 lg:self-start">
            <Card className="border border-zinc-200/90 bg-white/80 dark:border-zinc-800/80 dark:bg-zinc-950/40">
              <CardHeader>
                <CardTitle>{t("empresa.reputation")}</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="rounded-xl bg-gradient-to-r from-emerald-500/30 to-emerald-500/10 p-3 text-center ring-1 ring-emerald-500/50">
                  <div className="text-xs text-emerald-900/90 dark:text-emerald-100">{t("empresa.seal")}</div>
                  <div className="text-lg font-bold text-emerald-900 dark:text-emerald-200">{seal}</div>
                  <div className="text-xs text-emerald-900/90 dark:text-emerald-100">
                    {t("empresa.scoreOutOf10")} {reputation.score}/10
                  </div>
                </div>
                <FeatureItem
                  icon={<Radar className="h-4 w-4 text-emerald-300" />}
                  title={t("empresa.feature6mTitle")}
                  desc={t("empresa.feature6mDesc")}
                  content={`${t("empresa.responseWord")}: ${reputation.responseRate.toFixed(1)} | ${t("empresa.solutionWord")}: ${reputation.solutionRate.toFixed(1)}`}
                />
                <FeatureItem
                  icon={<Database className="h-4 w-4 text-emerald-300" />}
                  title={t("empresa.feature12mTitle")}
                  desc={t("empresa.feature12mDesc")}
                  content={`${t("empresa.feature12mContent")}: ${reputation.avgRating.toFixed(1)}/10`}
                />
                <FeatureItem
                  icon={<Clock3 className="h-4 w-4 text-emerald-300" />}
                  title={t("empresa.featureMetricsTitle")}
                  desc={t("empresa.featureMetricsDesc")}
                  content={`${t("empresa.featureMetricsContent")}: ${performance.avgResponseHours.toFixed(1)}h | ${t("empresa.featureMetricsSolution")}: ${performance.solutionIndex.toFixed(1)}%`}
                />
              </CardContent>
            </Card>
          </aside>

          <main className="col-span-12 space-y-4 lg:col-span-6">
            <Card className="border border-zinc-200/90 bg-white/80 dark:border-zinc-800/80 dark:bg-zinc-950/40">
              <CardContent className="pt-5">
                <div className="grid gap-2 md:grid-cols-3">
                  <input
                    value={query}
                    onChange={(e) => setQuery(e.target.value)}
                    placeholder={t("empresa.searchComplaintsPlaceholder")}
                    className="h-10 rounded-xl border border-zinc-200 bg-white px-3 text-sm text-zinc-900 outline-none focus:border-emerald-500/50 dark:border-zinc-800 dark:bg-zinc-950/70 dark:text-zinc-100"
                  />
                  <input
                    value={city}
                    onChange={(e) => setCity(e.target.value)}
                    placeholder={t("empresa.filterCityPlaceholder")}
                    className="h-10 rounded-xl border border-zinc-200 bg-white px-3 text-sm text-zinc-900 outline-none focus:border-emerald-500/50 dark:border-zinc-800 dark:bg-zinc-950/70 dark:text-zinc-100"
                  />
                  <select
                    value={status}
                    onChange={(e) => setStatus(e.target.value)}
                    className="h-10 rounded-xl border border-zinc-200 bg-white px-3 text-sm text-zinc-900 outline-none focus:border-emerald-500/50 dark:border-zinc-800 dark:bg-zinc-950/70 dark:text-zinc-100"
                  >
                    <option value="">{t("common.status.all")}</option>
                    <option value="pending">{t("common.status.pending")}</option>
                    <option value="reviewed">{t("empresa.statusReviewed")}</option>
                    <option value="resolved">{t("empresa.statusResolvedFem")}</option>
                    <option value="archived">{t("empresa.statusArchivedFem")}</option>
                  </select>
                </div>
              </CardContent>
            </Card>

            <Tabs.Root value={tab} onValueChange={(value) => setTab(value as EmpresaTab)}>
              <Tabs.List className="inline-flex flex-wrap rounded-xl bg-zinc-100/90 p-1 ring-1 ring-zinc-200/90 dark:bg-zinc-950/40 dark:ring-zinc-800/80">
                <Tabs.Trigger
                  value="latest"
                  className="rounded-lg px-3 py-2 text-sm text-zinc-600 transition data-[state=active]:bg-white data-[state=active]:text-zinc-900 data-[state=active]:shadow-sm dark:text-zinc-300 dark:data-[state=active]:bg-zinc-800 dark:data-[state=active]:text-zinc-100 dark:data-[state=active]:shadow-none"
                >
                  {t("empresa.tabLatest")}
                </Tabs.Trigger>
                <Tabs.Trigger
                  value="unanswered"
                  className="rounded-lg px-3 py-2 text-sm text-zinc-600 transition data-[state=active]:bg-white data-[state=active]:text-zinc-900 data-[state=active]:shadow-sm dark:text-zinc-300 dark:data-[state=active]:bg-zinc-800 dark:data-[state=active]:text-zinc-100 dark:data-[state=active]:shadow-none"
                >
                  {t("empresa.tabUnanswered")}
                </Tabs.Trigger>
                <Tabs.Trigger
                  value="responded"
                  className="rounded-lg px-3 py-2 text-sm text-zinc-600 transition data-[state=active]:bg-white data-[state=active]:text-zinc-900 data-[state=active]:shadow-sm dark:text-zinc-300 dark:data-[state=active]:bg-zinc-800 dark:data-[state=active]:text-zinc-100 dark:data-[state=active]:shadow-none"
                >
                  {t("empresa.tabResponded")}
                </Tabs.Trigger>
              </Tabs.List>
            </Tabs.Root>

            <div className="space-y-3">
              {complaints.map((complaint) => (
                <Card key={complaint.id} className="border border-zinc-200/90 bg-white/80 dark:border-zinc-800/80 dark:bg-zinc-950/40">
                  <CardContent className="pt-5">
                    <div className="mb-2 flex items-center justify-between text-xs text-zinc-400">
                      <span>{dateMap[complaint.id] ?? "-"}</span>
                      {complaint.author_id && complaint.author_label !== "Anónimo" ? (
                        <Link href={`/u/${complaint.author_id}`} className="underline-offset-2 hover:underline">
                          {complaint.author_label}
                        </Link>
                      ) : (
                        <span>{complaint.author_label}</span>
                      )}
                    </div>
                    <p className="text-sm text-zinc-800 dark:text-zinc-100">{complaint.content}</p>
                  </CardContent>
                </Card>
              ))}
              {complaints.length === 0 && (
                <Card>
                  <CardContent className="pt-5">
                    <p className="inline-flex items-center gap-2 text-sm text-zinc-300">
                      <TriangleAlert className="h-4 w-4 text-amber-300" />
                      {t("empresa.emptyComplaints")}
                    </p>
                  </CardContent>
                </Card>
              )}
            </div>
          </main>

          <aside className="col-span-12 space-y-4 lg:col-span-3 lg:sticky lg:top-24 lg:self-start">
            <Card className="border border-zinc-200/90 bg-white/80 dark:border-zinc-800/80 dark:bg-zinc-950/40">
              <CardHeader>
                <CardTitle>{t("empresa.about")}</CardTitle>
              </CardHeader>
              <CardContent className="text-sm text-zinc-700 dark:text-zinc-300">
                <p className="mb-2">
                  {t("empresa.taxId")}: {company.taxId || t("common.notInformed")}
                </p>
                <p className="leading-6 text-zinc-600 dark:text-zinc-400">{company.description || t("common.noDescription")}</p>
              </CardContent>
            </Card>
            <Card className="border border-zinc-200/90 bg-white/80 dark:border-zinc-800/80 dark:bg-zinc-950/40">
              <CardHeader>
                <CardTitle>{t("empresa.contacts")}</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2 text-sm">
                {company.website ? (
                  <a href={company.website} className="block text-emerald-700 hover:underline dark:text-emerald-300" target="_blank" rel="noreferrer">
                    {company.website}
                  </a>
                ) : (
                  <span className="text-zinc-500 dark:text-zinc-400">{t("empresa.websiteMissing")}</span>
                )}
                {company.ownerEmail ? (
                  <a href={`mailto:${company.ownerEmail}`} className="block text-emerald-700 hover:underline dark:text-emerald-300">
                    {company.ownerEmail}
                  </a>
                ) : null}
              </CardContent>
            </Card>
            {(isOwner || isAdmin) && (
              <FeatureItem
                icon={<Lock className="h-4 w-4 text-emerald-300" />}
                title={t("empresa.adminModeTitle")}
                desc={t("empresa.adminModeDesc")}
                content={t("empresa.adminModeContent")}
              />
            )}
          </aside>
        </div>

        <footer className="mt-8 rounded-2xl border border-zinc-200/90 bg-zinc-50/90 p-6 dark:border-transparent dark:bg-zinc-950/60 dark:ring-1 dark:ring-zinc-800/70">
          <div className="grid grid-cols-1 gap-4 md:grid-cols-4">
            <div className="border-b border-zinc-800/70 pb-3 md:border-b-0 md:border-r md:pr-4 md:pb-0">
              <h3 className="mb-2 text-sm font-semibold text-zinc-900 dark:text-zinc-100">{t("empresa.footerLinks")}</h3>
              <p className="text-xs text-zinc-400">{t("empresa.footerLinksDesc")}</p>
            </div>
            <div className="border-b border-zinc-800/70 pb-3 md:border-b-0 md:border-r md:pr-4 md:pb-0">
              <h3 className="mb-2 text-sm font-semibold text-zinc-900 dark:text-zinc-100">{t("empresa.footerCategories")}</h3>
              <p className="text-xs text-zinc-400">{t("empresa.footerCategoriesDesc")}</p>
            </div>
            <div className="border-b border-zinc-800/70 pb-3 md:border-b-0 md:border-r md:pr-4 md:pb-0">
              <h3 className="mb-2 text-sm font-semibold text-zinc-900 dark:text-zinc-100">{t("empresa.footerLegal")}</h3>
              <p className="text-xs text-zinc-400">{t("empresa.footerLegalDesc")}</p>
            </div>
            <div>
              <h3 className="mb-2 text-sm font-semibold text-zinc-900 dark:text-zinc-100">{t("empresa.footerSocial")}</h3>
              <p className="text-xs text-zinc-400">{t("empresa.footerSocialDesc")}</p>
            </div>
          </div>
          <div className="mt-4 flex items-center gap-2 text-xs text-zinc-500">
            <ShieldCheck className="h-4 w-4 text-emerald-400" />
            <span>{t("empresa.footerThemeNote")}</span>
          </div>
        </footer>
      </div>
    </div>
  );
}

